spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sachinkush007/cloud-config-server
#        username: sachinkush007
#        password: Sachin@7930
#cloud:
#  config:
#    server:
#      native:
#        search-locations : file:///{{D:\Sachin\Microservice\cloud-config-server}}
#    label : main
#  profiles:
#    active: native

server:
  port: 9196
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
